#ifndef SMTP_MTA_REXPRS_H
#define SMTP_MTA_REXPRS_H

/* COMMON: */

#define RE_CRLF "\\r\\n"
#define RE_SP " "

/* COMMANDS: */

#define RE_CMND_NOOP "NOOP" REXP_CRLF
#define RE_CMND_HELO "HELO" REXP_SP REXP_CRLF // TODO: add REXP DOMAIN
#define RE_CMND_EHLO "EHLO" REXP_SP REXP_CRLF // TODO: add REXP DOMAIN
#define RE_CMND_MAIL "MAIL FROM:" REXP_CRLF // TODO: add REXP for SENDER
#define RE_CMND_RCPT "RCPT TO:" REXP_CRLF // TODO: add REXP for RECEPIENT
#define RE_CMND_VRFY "VRFY" REXP_CRLF // TODO: add REXP for SENDER
#define RE_CMND_DATA "DATA" REXP_CRLF
#define RE_CMND_RSET "RSET" REXP_CRLF
#define RE_CMND_QUIT "QUIT" REXP_CRLF

/* MAIL CONTENT: */

#define RE_MAIL_DATA R_CRLF // TODO: add REXP for mail ascii data
#define RE_MAIL_END "." REXP_CRLF

/* RESPONSES: */

#define RE_RESP_READY 220
#define RE_RESP_CLOSE 221
#define RE_RESP_OK 250
#define RE_RESP_START_MAIL 354

#define RE_RESP_ERR_WRONG_CMND 500
#define RE_RESP_ERR_WRONG_ARGS 501
#define RE_RESP_ERR_NOT_IMPL_CMND 502
#define RE_RESP_ERR_BAD_SEQ 503
#define RE_RESP_ERR_MAILBOX_UNAVAIL 550
#define RE_RESP_ERR_MAILBOX_INCORRECT 553

#endif //SMTP_MTA_REXPRS_H
