#ifndef SMTP_MTA_SERVER_FSM_HANDLERS_H
#define SMTP_MTA_SERVER_FSM_HANDLERS_H

#include "server-fsm.h"

int HANDLE_ACCEPTED();

int HANDLE_CMND_HELO();
int HANDLE_CMND_EHLO();

int HANDLE_CMND_MAIL();
int HANDLE_CMND_RCPT();
int HANDLE_CMND_DATA();

int HANDLE_MAIL_DATA();
int HANDLE_MAIL_SAVED();
int HANDLE_MAIL_END();

int HANDLE_CMND_RSET();
int HANDLE_CLOSE();

#endif //SMTP_MTA_SERVER_FSM_HANDLERS_H
